### ISSUE TITLE
😎 Filter widget

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#597]
# Idea 

The idea is to make a more advanced widget which works similar to the already existing filter mechanism.
This would solve every idea we came up in #217 :

- [x] [my assigned cards](https://github.com/stefan-niedermann/nextcloud-deck/issues/217#issue-530183936)
- [x] [due cards](https://github.com/stefan-niedermann/nextcloud-deck/issues/217#issue-530183936)
- [x] [all cards from project X](https://github.com/stefan-niedermann/nextcloud-deck/issues/217#issue-530183936)
- [x] [All boards, special board](https://github.com/stefan-niedermann/nextcloud-deck/issues/217#issuecomment-562452717)
- [x] [All tags, special tags](https://github.com/stefan-niedermann/nextcloud-deck/issues/217#issuecomment-562452717)
- [x] [All, assigned to me](https://github.com/stefan-niedermann/nextcloud-deck/issues/217#issuecomment-562452717)

For the beginning we will start with only **one** possible `Account`, because otherwise the management of the `User`s will be the hell.

## Configuration

There are three important areas to configure, so maybe some kind of stepper / wizard would appropriate for this.

1. **Scope** (select **one** `Account`, then **n** `Board`s based on the selected `Account`)
  ![grafik](https://user-images.githubusercontent.com/4741199/87345022-b0f29e80-c54f-11ea-9a3e-a94ca8f2541f.png)
2. **Filter** (like the known filter mechanism)
  We will have to add a second row in the "tags" section for the origin `Board` of the correspond `Tag`, because there could be multiple `Tag`s with the same title and maybe even with the same color. For users this is not necessary because we only allow one `Account` at the beginning.
  ![grafik](https://user-images.githubusercontent.com/4741199/87344985-a20bec00-c54f-11ea-8e47-7722d6bbc156.png)
3. **Sort** by
  ![grafik](https://user-images.githubusercontent.com/4741199/87345674-b0a6d300-c550-11ea-9485-822ad938cb21.png)

## View

The actual view of the completely configured widget could be pretty similar to the [stack widget](https://github.com/stefan-niedermann/nextcloud-deck/pull/529) but should have sections [similar to the Notes app](https://raw.githubusercontent.com/stefan-niedermann/nextcloud-notes/d20a2fd086eebf0eb0f16e841de28d2f578337f9/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png) for the "highest" sorting criteria. Also the top headline does not represent the `Board` and its color, but the `Account` and the avatar.
It also needs to provide the ability to change the configuration because of its complex nature.

# Implementation

## Data structure

-- to be defined --

## UI

- [ ] `FilterWidgetConfigurationActivity`

**Comment by splashote** [comment]
hey,
great to see the progress on the widget.
what I would suggest is the following:
- open the selected card when clicking on it

- add a **+** button in the top right corner to easily add a card to the list displayed.

I see that the latter might not always be useful depending on the kind of 'filter set' you chose for it.
Anyway, I really miss it.

looking forward to the upcoming development, being ready to test in the beta channel.

cheers!

**Comment by stefan-niedermann** [comment]
Thank you for your input. The ➕ button will be possible because simply can display a choose dialog (just like the shortcut we already have when long-pressing the launcher icon).

Though this is out of scope for the first catch from my point of view - use the already existing [live tile](https://miro.medium.com/max/1012/0*zYn9jRHUGJTkE4CB.) or the [shortcut](https://miro.medium.com/max/3927/1*gfQYi_piiZ96d5XmObwOiQ.png).

**Comment by jakobroehrl** [comment]
@stefan-niedermann 
Do you have an idee when this awesome filter widget could be ready? Would love to test it. 
Would it be possible to create a widget that shows these upcoming cards? https://github.com/nextcloud/deck/issues/2231

**Comment by stefan-niedermann** [comment]
Not yet, sorry. We are busy with `ETag` support and some other stuff. Yes, i think it should be possible.

**Comment by desperateCoder** [comment]
![grafik](https://user-images.githubusercontent.com/6911132/97746932-72c3bf80-1aeb-11eb-9167-5139e9d7f7a2.png)

**Comment by stefan-niedermann** [comment]
![IMG_20201121_142954](https://user-images.githubusercontent.com/4741199/99878498-18a7ad00-2c06-11eb-9e02-f6c9d12b053c.jpg)

**Comment by desperateCoder** [comment]
Just realized:

> all cards from project X

(https://github.com/stefan-niedermann/nextcloud-deck/issues/217#issue-530183936)

Should we add that? Or maybe later on? not sure how desired this is... What dou you think? @stefan-niedermann? @jakobroehrl ?

**Comment by jakobroehrl** [comment]
I think this are the most useful filters:
 - my assigned cards
 - due cards

How long does it take to implement it?

**Comment by desperateCoder** [comment]
We're on it for a while now to be honest :sweat_smile: 

We're currently working on the "Upcoming Cards" widget: Cards assigned to me ordered by Due date. But we're prepared for more: a powerful, configurable filter widget. This might take a while to implement it really well, but while we build the basis to this, it would be interesting if we should also take projects into account. That's why I'm asking this now.

**Comment by desperateCoder** [comment]
Never mind, just added that.
